# Generated by Django 5.2.12 on 2026-03-31 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_source_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='project_pro_source__d4004f_idx',
            old_name='project_pro_source__d37c48_idx',
        ),
    ]
