# Generated by Django 5.2.12 on 2026-03-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_add_contact_account_to_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
    ]
